baseURL: https://rytisk.github.io/
languageCode: en-us
title: Supposed to be a Blog
theme: mini
paginate: 5
googleAnalytics: "G-LBPFB07FCQ"
enableEmoji: true

markup:
  highlight:
    guessSyntax: false
    style: friendly
    tabWidth: 4

social:
  github: https://github.com/rytisk

params:
  enableRSS: false
  enableComments: false
  enableGoogleAnalytics: true
  showPowerBy: false
  hiddenPostSummaryInHomePage: true
  copyright: '© 2024 rytisk'