baseURL: https://rytisk.github.io/
languageCode: en-us
title: Rytis Kaplūnas
paginate: 5
enableEmoji: true

markup:
  highlight:
    guessSyntax: false
    style: gruvbox
    tabWidth: 4
    linenos: false

social:
  github: https://github.com/rytisk

params:
  mainSections: ["posts"]
  enableRSS: false
  enableComments: false
  showPowerBy: false
  hiddenPostSummaryInHomePage: true
  copyright: '© 2026 rytisk'
